### ISSUE TITLE
Contributing to the erlang ftplugin

### ISSUE THREAD

**Issue by slarwise** [vim-erlang/vim-erlang-runtime#46]
Hi!

I was wondering if we can contribute to the erlang ftplugin through this repo. I think it would be nice to set some `path` and `include-search` related options, such as `suffixesadd`, `include` and `define` :)

**Comment by hcs42** [comment]
Hi @slarwise. It's a good idea.

Hi @oscarh. Since [you are the author](https://github.com/vim/vim/blob/cb80aa2d53e56d3aba3b3c439fb467f29a750c5e/runtime/ftplugin/erlang.vim) of `ftplugin/erlang.vim`, and there is no maintainer noted, this means that you are the maintainer. In practice, this means that Bram Moolenar accepts updates to `ftplugin/erlang.vim` only from you.

Are you OK with making this repo the home of `ftplugin/erlang.vim`? It is already the home of `syntax/erlang.vim` and `indent/erlang.vim`. I periodically send the latest versions of these files to Bram for inclusion in the Vim repository.

Would you like to remain the maintainer of the script? (Review PRs, sending the e-mails to Bram?)

**Comment by oscarh** [comment]
Hi!

I really don't mind if you take over responsibility for the ftplugin/erlang.vim! 

Unfortunately I haven't maintained my version of the repository for a long time. I also haven't been working with Erlang for a long time. This means my fork is probably / should be considered dead. I'm also not really a good candidate for reviewing pull requests.

**Comment by hcs42** [comment]
@oscarh Thank you, I'm happy to take over the maintainership. Good luck with your non-Erlang work! :)

@slarwise I will add `ftplugin/erlang.vim` to this repo (in a few days at most), and you will be able to base your contributions on it.

**Comment by slarwise** [comment]
That's great, thank you :)

**Comment by hcs42** [comment]
I added `ftplugin/erlang.vim` to this repository.

**Comment by hcs42** [comment]
@slarwise The `ftplugin/erlang.vim` script in the current `vim-erlang-runtime` master is now in Vim: https://github.com/vim/vim/blob/master/runtime/ftplugin/erlang.vim

Thanks again!

**Comment by slarwise** [comment]
Awesome, that's great 😀
